INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start group_by_license_number()...
INFO:root:Start get_license_number_group(iolskm18289)...
INFO:root:Starting is_us(iolskm18289)...
INFO:root:Start get_license_number_group(Y-95632547)...
INFO:root:Starting is_us(Y-95632547)...
INFO:root:Starting is_uk(Y-95632547)...
INFO:root:Start get_license_number_group(asd-893948-oo)...
INFO:root:Starting is_us(asd-893948-oo)...
INFO:root:Starting is_uk(asd-893948-oo)...
INFO:root:Starting is_ca(asd-893948-oo)...
INFO:root:Start get_license_number_group(x89f54j)...
INFO:root:Starting is_us(x89f54j)...
INFO:root:Starting is_uk(x89f54j)...
INFO:root:Starting is_ca(x89f54j)...
INFO:root:Start get_license_number_group(2sdk89033)...
INFO:root:Starting is_us(2sdk89033)...
INFO:root:Starting is_uk(2sdk89033)...
INFO:root:Starting is_ca(2sdk89033)...
INFO:root:Start get_license_number_group(asv-965412-op)...
INFO:root:Starting is_us(asv-965412-op)...
INFO:root:Starting is_uk(asv-965412-op)...
INFO:root:Starting is_ca(asv-965412-op)...
INFO:root:Start get_license_number_group(prvtyu90303)...
INFO:root:Starting is_us(prvtyu90303)...
INFO:root:Start get_license_number_group(x23f80f)...
INFO:root:Starting is_us(x23f80f)...
INFO:root:Starting is_uk(x23f80f)...
INFO:root:Starting is_ca(x23f80f)...
INFO:root:Start get_license_number_group(asn-382981-oi)...
INFO:root:Starting is_us(asn-382981-oi)...
INFO:root:Starting is_uk(asn-382981-oi)...
INFO:root:Starting is_ca(asn-382981-oi)...
INFO:root:Start get_license_number_group(T-85456932)...
INFO:root:Starting is_us(T-85456932)...
INFO:root:Starting is_uk(T-85456932)...
INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start group_by_license_number()...
INFO:root:Start get_license_number_group(iolskm18289)...
INFO:root:Starting is_us(iolskm18289)...
INFO:root:Start get_license_number_group(Y-95632547)...
INFO:root:Starting is_us(Y-95632547)...
INFO:root:Starting is_uk(Y-95632547)...
INFO:root:Start get_license_number_group(asd-893948-oo)...
INFO:root:Starting is_us(asd-893948-oo)...
INFO:root:Starting is_uk(asd-893948-oo)...
INFO:root:Starting is_ca(asd-893948-oo)...
INFO:root:Start get_license_number_group(x89f54j)...
INFO:root:Starting is_us(x89f54j)...
INFO:root:Starting is_uk(x89f54j)...
INFO:root:Starting is_ca(x89f54j)...
INFO:root:Start get_license_number_group(2sdk89033)...
INFO:root:Starting is_us(2sdk89033)...
INFO:root:Starting is_uk(2sdk89033)...
INFO:root:Starting is_ca(2sdk89033)...
INFO:root:Start get_license_number_group(asv-965412-op)...
INFO:root:Starting is_us(asv-965412-op)...
INFO:root:Starting is_uk(asv-965412-op)...
INFO:root:Starting is_ca(asv-965412-op)...
INFO:root:Start get_license_number_group(prvtyu90303)...
INFO:root:Starting is_us(prvtyu90303)...
INFO:root:Start get_license_number_group(x23f80f)...
INFO:root:Starting is_us(x23f80f)...
INFO:root:Starting is_uk(x23f80f)...
INFO:root:Starting is_ca(x23f80f)...
INFO:root:Start get_license_number_group(asn-382981-oi)...
INFO:root:Starting is_us(asn-382981-oi)...
INFO:root:Starting is_uk(asn-382981-oi)...
INFO:root:Starting is_ca(asn-382981-oi)...
INFO:root:Start get_license_number_group(T-85456932)...
INFO:root:Starting is_us(T-85456932)...
INFO:root:Starting is_uk(T-85456932)...
INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start group_by_license_number()...
INFO:root:Start get_license_number_group(iolskm18289)...
INFO:root:Starting is_us(iolskm18289)...
INFO:root:Start get_license_number_group(Y-95632547)...
INFO:root:Starting is_us(Y-95632547)...
INFO:root:Starting is_uk(Y-95632547)...
INFO:root:Start get_license_number_group(asd-893948-oo)...
INFO:root:Starting is_us(asd-893948-oo)...
INFO:root:Starting is_uk(asd-893948-oo)...
INFO:root:Starting is_ca(asd-893948-oo)...
INFO:root:Start get_license_number_group(x89f54j)...
INFO:root:Starting is_us(x89f54j)...
INFO:root:Starting is_uk(x89f54j)...
INFO:root:Starting is_ca(x89f54j)...
INFO:root:Start get_license_number_group(2sdk89033)...
INFO:root:Starting is_us(2sdk89033)...
INFO:root:Starting is_uk(2sdk89033)...
INFO:root:Starting is_ca(2sdk89033)...
INFO:root:Start get_license_number_group(asv-965412-op)...
INFO:root:Starting is_us(asv-965412-op)...
INFO:root:Starting is_uk(asv-965412-op)...
INFO:root:Starting is_ca(asv-965412-op)...
INFO:root:Start get_license_number_group(prvtyu90303)...
INFO:root:Starting is_us(prvtyu90303)...
INFO:root:Start get_license_number_group(x23f80f)...
INFO:root:Starting is_us(x23f80f)...
INFO:root:Starting is_uk(x23f80f)...
INFO:root:Starting is_ca(x23f80f)...
INFO:root:Start get_license_number_group(asn-382981-oi)...
INFO:root:Starting is_us(asn-382981-oi)...
INFO:root:Starting is_uk(asn-382981-oi)...
INFO:root:Starting is_ca(asn-382981-oi)...
INFO:root:Start get_license_number_group(T-85456932)...
INFO:root:Starting is_us(T-85456932)...
INFO:root:Starting is_uk(T-85456932)...
INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:
Traceback (most recent call last):
  File "/Users/locvdnguyen/Documents/courses-python/python-training/exercise06/filehandler.py", line 90, in load_csv_as_dictionaries
    data_from_csv = pd.read_csv(file_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1140, in _execute_mock_call
    raise effect
FileNotFoundError
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:
Traceback (most recent call last):
  File "/Users/locvdnguyen/Documents/courses-python/python-training/exercise06/filehandler.py", line 90, in load_csv_as_dictionaries
    data_from_csv = pd.read_csv(file_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1140, in _execute_mock_call
    raise effect
FileNotFoundError
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:
Traceback (most recent call last):
  File "/Users/locvdnguyen/Documents/courses-python/python-training/exercise06/filehandler.py", line 90, in load_csv_as_dictionaries
    data_from_csv = pd.read_csv(file_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1140, in _execute_mock_call
    raise effect
FileNotFoundError
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:
Traceback (most recent call last):
  File "/Users/locvdnguyen/Documents/courses-python/python-training/exercise06/filehandler.py", line 90, in load_csv_as_dictionaries
    data_from_csv = pd.read_csv(file_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1140, in _execute_mock_call
    raise effect
FileNotFoundError
INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:
Traceback (most recent call last):
  File "/Users/locvdnguyen/Documents/courses-python/python-training/exercise06/filehandler.py", line 90, in load_csv_as_dictionaries
    data_from_csv = pd.read_csv(file_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1140, in _execute_mock_call
    raise effect
FileNotFoundError
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:'Exception' object has no attribute 'to_dict'
INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:'Exception' object has no attribute 'to_dict'
INFO:root:Start group_by_license_number()...
INFO:root:Start get_license_number_group(iolskm18289)...
INFO:root:Starting is_us(iolskm18289)...
INFO:root:Start get_license_number_group(Y-95632547)...
INFO:root:Starting is_us(Y-95632547)...
INFO:root:Starting is_uk(Y-95632547)...
INFO:root:Start get_license_number_group(asd-893948-oo)...
INFO:root:Starting is_us(asd-893948-oo)...
INFO:root:Starting is_uk(asd-893948-oo)...
INFO:root:Starting is_ca(asd-893948-oo)...
INFO:root:Start get_license_number_group(x89f54j)...
INFO:root:Starting is_us(x89f54j)...
INFO:root:Starting is_uk(x89f54j)...
INFO:root:Starting is_ca(x89f54j)...
INFO:root:Start group_by_license_number()...
INFO:root:Start get_license_number_group(iolskm18289)...
INFO:root:Starting is_us(iolskm18289)...
INFO:root:Start get_license_number_group(Y-95632547)...
INFO:root:Starting is_us(Y-95632547)...
INFO:root:Starting is_uk(Y-95632547)...
INFO:root:Start get_license_number_group(asd-893948-oo)...
INFO:root:Starting is_us(asd-893948-oo)...
INFO:root:Starting is_uk(asd-893948-oo)...
INFO:root:Starting is_ca(asd-893948-oo)...
INFO:root:Start get_license_number_group(x89f54j)...
INFO:root:Starting is_us(x89f54j)...
INFO:root:Starting is_uk(x89f54j)...
INFO:root:Starting is_ca(x89f54j)...
INFO:root:Start group_by_license_number()...
INFO:root:Start get_license_number_group(iolskm18289)...
INFO:root:Starting is_us(iolskm18289)...
INFO:root:Start get_license_number_group(Y-95632547)...
INFO:root:Starting is_us(Y-95632547)...
INFO:root:Starting is_uk(Y-95632547)...
INFO:root:Start get_license_number_group(asd-893948-oo)...
INFO:root:Starting is_us(asd-893948-oo)...
INFO:root:Starting is_uk(asd-893948-oo)...
INFO:root:Starting is_ca(asd-893948-oo)...
INFO:root:Start get_license_number_group(x89f54j)...
INFO:root:Starting is_us(x89f54j)...
INFO:root:Starting is_uk(x89f54j)...
INFO:root:Starting is_ca(x89f54j)...
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:
Traceback (most recent call last):
  File "/Users/locvdnguyen/Documents/courses-python/python-training/exercise06/filehandler.py", line 90, in load_csv_as_dictionaries
    data_from_csv = pd.read_csv(file_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1140, in _execute_mock_call
    raise effect
FileNotFoundError
INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:'Exception' object has no attribute 'to_dict'
INFO:root:Start group_by_license_number()...
INFO:root:Start get_license_number_group(iolskm18289)...
INFO:root:Starting is_us(iolskm18289)...
INFO:root:Start get_license_number_group(Y-95632547)...
INFO:root:Starting is_us(Y-95632547)...
INFO:root:Starting is_uk(Y-95632547)...
INFO:root:Start get_license_number_group(asd-893948-oo)...
INFO:root:Starting is_us(asd-893948-oo)...
INFO:root:Starting is_uk(asd-893948-oo)...
INFO:root:Starting is_ca(asd-893948-oo)...
INFO:root:Start get_license_number_group(x89f54j)...
INFO:root:Starting is_us(x89f54j)...
INFO:root:Starting is_uk(x89f54j)...
INFO:root:Starting is_ca(x89f54j)...
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:
Traceback (most recent call last):
  File "/Users/locvdnguyen/Documents/courses-python/python-training/exercise06/filehandler.py", line 90, in load_csv_as_dictionaries
    data_from_csv = pd.read_csv(file_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1140, in _execute_mock_call
    raise effect
FileNotFoundError
INFO:root:Start load_csv_as_dictionaries...
INFO:root:Start load_csv_as_dictionaries...
ERROR:root:'Exception' object has no attribute 'to_dict'
